### ISSUE TITLE
EPEL 8

### ISSUE THREAD

**Issue by dgoetz** [Icinga/icinga-packaging#134]
# Tasks

- [x] Replace RHEL8 container with CentOS8 
- [x] Rebuild/add packages
  - [x] rpm-icinga2
  - [x] rpm-icingaweb2 (PHP versions from SCL?)
  - [x] Provide icinga-rpm-release RPM

# Original request

RHEL 8 is now available: https://developers.redhat.com/blog/2019/05/07/red-hat-enterprise-linux-8-now-generally-available/

So we will have to wait for CentOS 8 and EPEL to become available, but this is typically a time-frame of a month, so we should be prepared.

**Comment by dnsmichi** [comment]
The good news: Boost 1.66 is included, seems that we don't need EPEL for it. https://access.redhat.com/documentation/en-us/red_hat_enterprise_linux/8/html-single/8.0_release_notes/index#platform-tools

**Comment by lazyfrosch** [comment]
But we need EPEL for nagios/monitoring plugins...

**Comment by dnsmichi** [comment]
Sure, but we can start building now :) I wouldn't publish this anyway up until Centos isn't ready :)

**Comment by lazyfrosch** [comment]
No we can't without using a RedHat Devel Subscription, UBI will not allow us building RPMs. I tested this already.

**Comment by mphilipps** [comment]
From what I have gathered epel8 unlikely to be ready in the next few weeks, so a lack of nagios/monitoring plugins are a bit of an issue.

What would be  the issue with using a RedHat Devel Subscription? Is building rpms not considered  development use?

**Comment by dgoetz** [comment]
It is not a real issue but handling subscriptions for the Docker containers used in our Build environment is only possible with a Red Hat Enterprise Linux Server as Host, so it would require additional Build hosts to be created and as you correctly said without EPEL ready for other packages it simply makes no sense for us.

**Comment by lazyfrosch** [comment]
I already prepared some build containers based on RHEL8, we are currently in discussion how to release for RHEL8.

Since we do not built or distribute the nagios/monitoring plugins that might be a problem :)

@dgoetz: We can activate the container directly, like we do for SLES

**Comment by lazyfrosch** [comment]
Icinga 2 has been published for RHEL 8:

https://packages.icinga.com/epel/

Also the RC1 for 2.11 is availble there.

As we do not build monitoring-plugins or nagios-plugins you still have to do this on your own.

Icinga Web 2 and other packages are likely to come when CentOS 8 is ready.

**Comment by dgoetz** [comment]
Status for CentOS 8 can be found on https://wiki.centos.org/About/Building_8 which is currently in RC state.
Status for EPEL is it is initially released without modularity (planned for 8.1) and starts now to fill with packages. It still uses nagios-plugins (instead of monitoring-plugins) which are currently only in epel-testing except of nagios-plugins-nrpe which has already landed in epel.

**Comment by dnsmichi** [comment]
CentOS 8 is available, yet without EPEL we still have to wait.

**Comment by m4rx0** [comment]
@dsnmichi: without EPEL? EPEL 8 was initially released in mid august 2019, right?

https://lwn.net/Articles/796202/

**Comment by mphilipps** [comment]
Looks like epel8 now also has the nagios/monitoring plugins:

https://mirror.uic.edu/EPEL/8/Everything/x86_64/Packages/n/

Going to see how far I can get with a RHEL 8 vm.

**Comment by dnsmichi** [comment]
@m4rx0 interesting, thanks. Maybe it took them a while to publish the plugin package there. 

From what I read on Twitter, Docker base images will be published next week or so. This makes it easier to test and integrate then as well.

**Comment by mphilipps** [comment]
It appears that **perl-Nagios-Plugin** is still missing.

**Comment by JSkolnik** [comment]
When will icingaweb2 / icingacli be available for RHEL8 / Centos8?
Complete Icinga2 Master support on Centos8?

**Comment by Mikesch-mp** [comment]
Any news about releaseing packages for icingaweb2?

**Comment by dnsmichi** [comment]
We will update the issue once someone is actively working on this. Not before OSMC though.

**Comment by cite** [comment]
currently, installation on CentOS 8 fails with:

```
# dnf install icinga2
Last metadata expiration check: 0:13:05 ago on Fri 08 Nov 2019 10:50:36 AM CET.
Error: 
 Problem: package icinga2-2.11.2-1.el7.icinga.x86_64 requires icinga2-bin = 2.11.2-1.el7.icinga, but none of the providers can be installed
  - cannot install the best candidate for the job
  - nothing provides libboost_context.so.1.69.0()(64bit) needed by icinga2-bin-2.11.2-1.el7.icinga.x86_64
  - nothing provides libboost_coroutine.so.1.69.0()(64bit) needed by icinga2-bin-2.11.2-1.el7.icinga.x86_64
  - nothing provides libboost_date_time.so.1.69.0()(64bit) needed by icinga2-bin-2.11.2-1.el7.icinga.x86_64
  - nothing provides libboost_filesystem.so.1.69.0()(64bit) needed by icinga2-bin-2.11.2-1.el7.icinga.x86_64
  - nothing provides libboost_program_options.so.1.69.0()(64bit) needed by icinga2-bin-2.11.2-1.el7.icinga.x86_64
  - nothing provides libboost_regex.so.1.69.0()(64bit) needed by icinga2-bin-2.11.2-1.el7.icinga.x86_64
  - nothing provides libboost_system.so.1.69.0()(64bit) needed by icinga2-bin-2.11.2-1.el7.icinga.x86_64
  - nothing provides libboost_thread.so.1.69.0()(64bit) needed by icinga2-bin-2.11.2-1.el7.icinga.x86_64
```

It seems that the latest version provided in CentOS 8 is currently 1.66.0.

**Comment by mphilipps** [comment]
icinga2-2.11.2-1.**el7**.icinga.x86_64

That looks wrong, that should be el8. Do you have any old repos from CentOS 7 included?

**Comment by cite** [comment]
@mphilipps You are, of course, right. I rest my case!

**Comment by bro-hm** [comment]
Would you recommend to wait for the resolution or is it better to just setup icinga2 on Centos7 for now?

**Comment by dnsmichi** [comment]
https://icinga.com/2019/11/21/package-updates-rhel-centos-8-sles-15-sp1-fedora-31-opensuse-15-1/
