### ISSUE TITLE
openSUSE Leap 15.1

### ISSUE THREAD

**Issue by manfredw** [Icinga/icinga-packaging#141]
# Tasks

- [x] Docker build container
- [x] Adjust rpm-icinga2
- [x] Test and release 

# Original Request

Please add support for openSUSE 15.1.
Lifecycle of 15.0 is planned to end with Nov. 2019

**Comment by lazyfrosch** [comment]
Thanks for the heads up, we will take care of it

**Comment by lgraziosi** [comment]
SUSE Enterprise Linux 15 SP1 was also released on July.  
SLES15 SP0 will end its lifecycle on 31 Dec 2019.  
Support for this would be nice.  
Thanks.

**Comment by DavidLiedke** [comment]
> 
> 
> Thanks for the heads up, we will take care of it

Is there any news on this? I can see the folder but it has no content yet.

**Comment by dnsmichi** [comment]
@htriem Please take care tomorrow morning from the things we've learned today :)

**Comment by dnsmichi** [comment]
https://icinga.com/2019/11/21/package-updates-rhel-centos-8-sles-15-sp1-fedora-31-opensuse-15-1/
