### ISSUE TITLE
Fedora 31

### ISSUE THREAD

**Issue by Mithi83** [Icinga/icinga-packaging#164]
# Tasks

- [x] Docker build container
- [x] Adopt rpm-icinga2 for f31
- [x] Test and release packages

# Original Request

Fedora 31 was recently released. Please consider building related RPMs. Thanks.

**Comment by dnsmichi** [comment]
https://icinga.com/2019/11/21/package-updates-rhel-centos-8-sles-15-sp1-fedora-31-opensuse-15-1/
