### ISSUE TITLE
IcingaDB packages

### ISSUE THREAD

**Issue by dnsmichi** [Icinga/icinga-packaging#167]
# Tasks

- [x] Packages
  - [x] icinga-redis as package 
  - [x] icingadb
- [x] Prepare current build containers

## icinga-redis

- [x] Port 6380 by default
- [x] Build supported platforms
   - [x] EPEL 7 + 8
   - [x] SLES 15
   - [x] Debian 10 Buster
   - [x] Ubuntu 18.04 Bionic
- [x] Remove service file
   - [x] EPEL 7 + 8
   - [x] SLES 15
   - [x] Debian 10 Buster
   - [x] Ubuntu 18.04 Bionic

## icingadb-redis

- [x] Add as package to Icinga DB build repository:
   - [x] EPEL 7 + 8
   - [x] SLES 15
   - [x] Debian 10 Buster
   - [x] Ubuntu 18.04 Bionic

## icingadb

- [x] Build supported platforms
   - [x] EPEL 7 + 8
   - [x] SLES 15
   - [x] Debian 10 Buster
   - [x] Ubuntu 18.04 Bionic
- [x] Snapshot packages
- [ ] Prepare RC testing branch/release

**Comment by dnsmichi** [comment]
`icinga-redis` running in CentOS 8 Docker:

<img width="1546" alt="Screen Shot 2019-11-28 at 13 50 50" src="https://user-images.githubusercontent.com/382049/69807669-28083c00-11e6-11ea-96bb-4fb9c27f00cf.png">

**Comment by dnsmichi** [comment]
`icinga-redis` running in CentOS 7 Docker:

<img width="1546" alt="Screen Shot 2019-11-28 at 13 54 42" src="https://user-images.githubusercontent.com/382049/69807879-ad8bec00-11e6-11ea-9ebf-d540dbec1746.png">

**Comment by dnsmichi** [comment]
SLES 15.1

```
Overall download size: 3.0 MiB. Already cached: 0 B. After the operation, additional 17.4 MiB will be used.
Continue? [y/n/v/...? shows all options] (y): y
Retrieving package icinga-redis-5.0.7-1.x86_64                                                                                               (1/1),   3.0 MiB ( 17.4 MiB unpacked)
Retrieving: icinga-redis-5.0.7-1.x86_64.rpm ................................................................................................................................[done]

Checking for file conflicts: ...............................................................................................................................................[done]
(1/1) Installing: icinga-redis-5.0.7-1.x86_64 ..............................................................................................................................[done]
Additional rpm output:
[/usr/lib/tmpfiles.d/icinga-redis.conf:2] Line references path below legacy directory /var/run/, updating /var/run/redis/ → /run/redis/; please update the tmpfiles.d/ drop-in file accordingly.
[/usr/lib/tmpfiles.d/icinga-redis.conf:2] Unknown user 'redis'.
Failed to connect to bus: No such file or directory
See /usr/share/doc/packages/icinga-redis/README.SUSE to continue


build@334999794d71:/> id icinga-redis
uid=482(icinga-redis) gid=482(icinga-redis) groups=482(icinga-redis)
```

**Comment by dnsmichi** [comment]
Fixed in a new -2 revision.

<img width="1546" alt="Screen Shot 2019-11-28 at 15 30 59" src="https://user-images.githubusercontent.com/382049/69814296-30677380-11f4-11ea-8486-210a62b38ff0.png">

**Comment by dnsmichi** [comment]
Debian 10.

<img width="1546" alt="Screen Shot 2019-11-28 at 15 48 16" src="https://user-images.githubusercontent.com/382049/69815406-89380b80-11f6-11ea-99a7-c2cff45b49c8.png">

Ubuntu Bionic.

<img width="1546" alt="Screen Shot 2019-11-28 at 15 49 56" src="https://user-images.githubusercontent.com/382049/69815551-d9af6900-11f6-11ea-9a63-d227082f4f93.png">

**Comment by dnsmichi** [comment]
@N-o-X is fixing the systemd service for Debian/Ubuntu.

**Comment by dnsmichi** [comment]
Debian Buster 10 with Systemd in a Vagrant VM.

<img width="1546" alt="Screen Shot 2019-11-29 at 09 54 40" src="https://user-images.githubusercontent.com/382049/69856628-5c373780-128e-11ea-9e55-cb3433947ae7.png">

**Comment by dnsmichi** [comment]
icingadb snapshot packages have been uploaded.
