### ISSUE TITLE
SLES 15 SP1

### ISSUE THREAD

**Issue by dnsmichi** [Icinga/icinga-packaging#168]
# Tasks

- [x] Docker build image creation
- [x] Adjust rpm-icinga2
- [x] Test, snapshot, release

**Comment by lgraziosi** [comment]
Sorry to bother you guys, but the SLES 15 SP1 repo is not working right now for icinga2 RPMs. It's only working for icingaweb2 RPMs.  
I think that's because the RPMs are in a subfolder called "icinga2" instead.  
Thanks! Keep up the good work.

**Comment by lazyfrosch** [comment]
@lgraziosi an update for the metadata did fail, thanks for the heads-up!

It should work now!

**Comment by lgraziosi** [comment]
I can confirm, it's working now! Thanks.

**Comment by dnsmichi** [comment]
https://icinga.com/2019/11/21/package-updates-rhel-centos-8-sles-15-sp1-fedora-31-opensuse-15-1/
